"""Data types for sampling from language models.

This module defines the core data structures used to represent model outputs and batches
of samples during inference.
"""
from dataclasses import dataclass
from typing import Dict, List, Union


@dataclass(slots=True, kw_only=True)
class Sample:
    """A single sample generated by the language model.

    Represents one model-generated response along with associated metadata like
    probabilities and evaluation metrics.

    Attributes:
        response: Raw text response from the model
        tokens: Tokenized form of the response as integer IDs
        mask: Binary mask for loss computation (True=include, False=exclude)
        log_probs: Log probabilities for each generated token
        reward: Scalar quality metric for the response
        is_correct: Whether the response meets correctness criteria
    """
    response: str
    tokens: List[int]
    mask: List[bool]
    log_probs: List[float]
    reward: float
    is_correct: bool


@dataclass(slots=True, kw_only=True)
class SampleBatch:
    """A batch of model-generated samples sharing the same prompt.

    Groups multiple samples together with their shared context and aggregate metrics.

    Attributes:
        prompt: Input prompt text used to generate the samples
        prompt_tokens: Tokenized form of the prompt as integer IDs
        samples: List of generated Sample objects
        metrics: Aggregate statistics over the batch (e.g. mean reward)
    """
    prompt: str
    prompt_tokens: List[int]
    samples: List[Sample]
    metrics: Dict[str, Union[float, int]]